version: '3.1'

services:
  db:
    image: postgres:15
    container_name: hotelbooking_postgres
    restart: always
    environment:
      POSTGRES_DB: hotelbooking_db
      POSTGRES_USER: hotelbooking_user
      POSTGRES_PASSWORD: hotelbooking_pass
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/src/main/resources/init.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: